[package]
name = "Kether_Internal_Services_Server"
version = "0.0.1" #Rolling release... I don't mind changing this in future
edition = "2024"
authors = ["Dominik Adrian Grzywak <starterx4@gmail.com>"]
description = "Internal Services Server for the Kether L4D2 server website"
license = "GPL-3.0-only"
rust-version = "1.85"
homepage = "kether.pl"

[dependencies]
SC_Sub_Poster = { git = "https://github.com/KetherPL/SC_Sub_Poster.git" }
#SC_Sub_Poster = { path = "../Kether.pl-sub-poster-rust" }
clap = { version = "4.5.32", features = ["derive", "std"] }
colored = { version = "3.0.0", optional = true }
diesel = { version = "2.2.8", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"], optional = true }
gamedig = { version = "0.6.1", optional = true }
rocket = { version = "0.5.1", features = ["json"], optional = true }
rocket_cors = { version = "0.6.0", optional = true }
rocket_dyn_templates = { version = "0.1.0", features = ["handlebars"], optional = true }
rust-ini = { version = "0.21.1", features = ["inline-comment"], optional = true }
serde_json = "1.0.140"
steam-rs = { version = "0.5.1", optional = true }
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
once_cell = "1.19.0"

# The default release profile. It contains all optimizations, without
# sacrificing debug info. With this profile (like in the standard
# release profile), the debug info and the stack traces will still be available.
[profile.release]
lto = true
strip = true

[features]
default = ["kether_meta", "sat"] # Features starter pack
    kether_meta = ["rest_sqlite", "rest_steam", "server_query", "rest_call_for_sub", "fastdl"] # Meta package for Kether's needs
    sat = ["rest_api"] # Satanixon's/StarterX4's-specific features ¯\_(ツ)_/¯
        fastdl = ["rest_api", "dep:rocket_dyn_templates"] # FastDL http(!) server – for Source/GoldSrc games. Both for custom server content (e.g. maps, models, sounds) and (in our usecase) MOTDs.
                # /↑\ Don't forget pass it through the http. Source/GoldSrc games don't support https for FastDL.
        rest_sqlite = ["cfg", "rest_api", "dep:diesel"] # REST API – database part for website (binds, bind suggestions, commands)
        rest_steam = ["cfg", "rest_api", "dep:steam-rs"] # REST API – Steam part for website (fetch userdata, check if owns appid=550 (L4D2))
        server_query = ["dep:gamedig"] # Query L4D2 servers (either through CLI or REST API)
        rest_call_for_sub = ["cfg", "rest_api"] # REST API – Uses NodeJS to post `!sub` requests on the Steam Group Chat
            cfg = ["dep:colored", "dep:rust-ini"] # KISS.ini config – database file path, Steam Web API key
            rest_api = ["dep:rocket", "dep:rocket_cors"] # Base REST API support
