;; The database.sqlite file path or file name if the database_relative_dir option is true. =
database_path=kether.sqlite
;; Is the database in the same dir as the executable? If yes, don't forget to put just a file NAME in the database_path option. =
;; False = any directory that the shell is already in
database_relative_dir=true
;; Steam Web API key that will be utilized to fetch Steam user data (e.g. name, avatar, etc).
steam_web_api_key=
